# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_MARKET:      [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MARKET]

    providers:
        in_memory:
            memory: ~
        user:
            entity:
                class: AppBundle\Entity\User
                property: email

    #un firewall (ou pare-feu) cherche à vérifier
    #que vous êtes bien celui que vous prétendez être. Ici,
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: index
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: index

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /film/, roles: ROLE_USER }
        - { path: /preference, roles: ROLE_USER }
