<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllFilm(int $page,int $nbPerPage)
    {
        $query = $this->createQueryBuilder('f')->getQuery();

        $query->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
