<?php

namespace AppBundle\Repository;

/**
 * SagaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SagaRepository extends \Doctrine\ORM\EntityRepository
{
}
