<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $search
     * @return array
     */
    public function searchUser(string $search){

        $query = $this->createQueryBuilder('search')
            ->select('u')
            ->from(User::class, 'u')
            ->where('u.pseudo LIKE :word')
            ->setParameter('word','%'.$search.'%')
            ->getQuery()
            ->getResult()
        ;
        return $query;
    }
}
